2021-03-10 23:53:40,522 INFO    Thread-11 :12088 [wandb_setup.py:_flush():69] setting env: {'project': 'uncategorized', 'entity': 'avyay', 'root_dir': 'C:\\Users\\rao_a\\PythonCPU\\Deep Learning\\CS6910-Assignments-1\\Assignment1\\Avyay', 'sweep_id': 'mbcm7lra', 'run_id': 'dyxs57fe', 'sweep_param_path': 'C:\\Users\\rao_a\\PythonCPU\\Deep Learning\\CS6910-Assignments-1\\Assignment1\\Avyay\\wandb\\sweep-mbcm7lra\\config-dyxs57fe.yaml'}
2021-03-10 23:53:40,522 INFO    Thread-11 :12088 [wandb_setup.py:_flush():69] setting login settings: {}
2021-03-10 23:53:40,523 INFO    Thread-11 :12088 [wandb_init.py:_log_setup():334] Logging user logs to C:\Users\rao_a\PythonCPU\Deep Learning\CS6910-Assignments-1\Assignment1\Avyay\wandb\run-20210310_235340-dyxs57fe\logs\debug.log
2021-03-10 23:53:40,524 INFO    Thread-11 :12088 [wandb_init.py:_log_setup():335] Logging internal logs to C:\Users\rao_a\PythonCPU\Deep Learning\CS6910-Assignments-1\Assignment1\Avyay\wandb\run-20210310_235340-dyxs57fe\logs\debug-internal.log
2021-03-10 23:53:40,525 INFO    Thread-11 :12088 [wandb_init.py:init():367] calling init triggers
2021-03-10 23:53:40,525 INFO    Thread-11 :12088 [wandb_init.py:init():374] wandb.init called with sweep_config: {'epochs': 5, 'n_layers': 3}
config: {'n_layers': 3, 'layer_size': 32, 'weight_decay': 0, 'lr': 0.001, 'optimizer': 'sgd', 'batch_size': 32, 'init_method': 'random', 'activation': 'relu', 'epochs': 5}
2021-03-10 23:53:40,525 INFO    Thread-11 :12088 [wandb_init.py:init():389] re-initializing run, found existing run on stack: dyxs57fe
2021-03-10 23:53:40,530 INFO    Thread-11 :12088 [wandb_run.py:finish():1135] finishing run avyay/uncategorized/dyxs57fe
2021-03-10 23:53:40,531 INFO    Thread-11 :12088 [jupyter.py:save_history():320] not saving jupyter history
2021-03-10 23:53:40,531 INFO    Thread-11 :12088 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-03-10 23:53:40,531 INFO    Thread-11 :12088 [wandb_init.py:_jupyter_teardown():266] cleaning up jupyter logic
2021-03-10 23:53:40,531 INFO    Thread-11 :12088 [wandb_run.py:_atexit_cleanup():1446] got exitcode: 0
2021-03-10 23:53:40,532 INFO    Thread-11 :12088 [wandb_run.py:_restore():1418] restore
2021-03-10 23:53:41,782 INFO    Thread-11 :12088 [wandb_run.py:_wait_for_finish():1568] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 921
  total_bytes: 921
}

2021-03-10 23:53:43,784 INFO    Thread-11 :12088 [wandb_run.py:_wait_for_finish():1568] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 4554
  total_bytes: 4554
}

2021-03-10 23:53:45,786 INFO    Thread-11 :12088 [wandb_run.py:_wait_for_finish():1568] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 4554
  total_bytes: 4554
}

2021-03-10 23:53:46,981 INFO    Thread-11 :12088 [wandb_run.py:_show_files():1790] logging synced files
2021-03-10 23:53:46,988 INFO    Thread-11 :12088 [wandb_init.py:init():416] starting backend
2021-03-10 23:53:46,989 INFO    Thread-11 :12088 [backend.py:_multiprocessing_setup():71] multiprocessing start_methods=spawn, using: spawn
2021-03-10 23:53:46,995 INFO    Thread-11 :12088 [backend.py:ensure_launched():123] starting backend process...
2021-03-10 23:53:47,093 INFO    Thread-11 :12088 [backend.py:ensure_launched():128] started backend process with pid: 1040
2021-03-10 23:53:47,094 INFO    Thread-11 :12088 [wandb_init.py:init():421] backend started and connected
2021-03-10 23:53:47,095 INFO    Thread-11 :12088 [wandb_run.py:_config_callback():733] config_cb None None {'epochs': 5, 'n_layers': 3}
2021-03-10 23:53:47,095 INFO    Thread-11 :12088 [wandb_init.py:init():461] updated telemetry
2021-03-10 23:53:47,096 INFO    Thread-11 :12088 [wandb_init.py:init():480] communicating current version
2021-03-10 23:53:50,105 INFO    Thread-11 :12088 [wandb_init.py:init():485] got version response upgrade_message: "wandb version 0.10.22 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-03-10 23:53:50,106 INFO    Thread-11 :12088 [wandb_init.py:init():493] communicating run to backend with 30 second timeout
2021-03-10 23:53:50,655 INFO    Thread-11 :12088 [wandb_init.py:init():518] starting run threads in backend
2021-03-10 23:53:52,516 INFO    Thread-11 :12088 [wandb_run.py:_console_start():1476] atexit reg
2021-03-10 23:53:52,519 INFO    Thread-11 :12088 [wandb_run.py:_redirect():1339] redirect: SettingsConsole.WRAP
2021-03-10 23:53:52,519 INFO    Thread-11 :12088 [wandb_run.py:_redirect():1374] Wrapping output streams.
2021-03-10 23:53:52,520 INFO    Thread-11 :12088 [wandb_run.py:_redirect():1390] Redirects installed.
2021-03-10 23:53:52,520 INFO    Thread-11 :12088 [wandb_init.py:init():542] run started, returning control to user process
2021-03-10 23:53:58,484 INFO    Thread-11 :12088 [wandb_run.py:finish():1135] finishing run avyay/uncategorized/dyxs57fe
